parameters:
    notification_class:
    userNotification_class:

services:
    joubjoub_notification.userNotification_manager:
        class: Joubjoub\NotificationBundle\Manager\UserNotificationManager
        arguments: [@doctrine.orm.entity_manager, "%userNotification_class%" ]

    joubjoub_notification.notification:
       class: Joubjoub\NotificationBundle\Notification
       arguments: [@joubjoub_notification.notification_manager]
